version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing aws cli
          working_directory: ./app/build
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo  pip3 install awsebcli --upgrade
      - run: cd ./app && npm install && npm run build
      - run: zip << pipeline.number >> -r .
      - aws-s3/sync:
          from: << pipeline.number >>.zip
          to: 's3://circle-ci-buckets'
    
       
workflows:
  deploy:
    jobs: 
      - build
      
# - run: cd ./app && npm install && npm run build
#       - aws-s3/sync:
#           from: ./app/build 
#           to  : s3://circle-ci-bucket
# #       - run: aws s3 sync ./app/build s3://circle-ci-bucket
