version: '2.1'
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  build_deploy:
    machine: 
      image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: |
          sudo apt-get update
          sudo apt install python3-pip
          sudo pip3 install awsebcli --upgrade
      - run: cd ./app && npm install && npm run build
      - aws-s3/sync:
          aws-access-key-id: $MY_AWS_ACCESS_KEY
          aws-region: $AWS_REGION
          aws-secret-access-key: $MY_AWS_SECRET_KEY
          from: ./app/build 
          to  : s3://circle-ci-bucket
#       - run: aws s3 sync ./app/build s3://circle-ci-bucket
          
      
workflows:
  execute_jobs:
    jobs:
      - build_deploy
       
   
      
